// Takes the auto-generated `__auto.index.js` file and bundles its contents into `/public/js/__bundle.globals.js`
// The output is a single IIFE containing all utility functions, globally accessible via `window`

import nodeResolve from "@rollup/plugin-node-resolve";
import terser from "@rollup/plugin-terser";

export default {
	input: "src/utils/__auto.index.js", // Entry point auto-generated by `generate-utils-map.mjs`
	output: {
		file: "public/js/__bundle.globals.js", // Final bundled output used in `<Script />` components
		format: "iife", // Wraps all code in a function and runs immediately
		inlineDynamicImports: true, // Ensures all modules are bundled into a single file
	},
	plugins: [
		nodeResolve(), // Resolve modules from node_modules
		terser(), // Minify output
	],
	treeshake: false, // Ensures no imported functions are stripped out even if unused
};
